Recommend from precalculated data
cs-22-sw-8-07/recommender_system pull request #4
Opened 2022-04-25 09:49 UTC by JeppeLindberg

2022-04-25 18:48 UTC, Determinatoro commented on src/main.py
> +        if len(args) > 2:
```if len(args) > 3:```

3 er 4. argument ikke 2

2022-04-25 18:49 UTC, Determinatoro commented on src/recommender.py
> +        return service_response_playlist_json(tracks_formatted, location.name, offset)
location i stedet for location.name, så der kan blive returneret en int i stedet for en string

2022-04-25 18:49 UTC, Determinatoro commented on src/service_response.py
>              "location_type": location,
location.value så der blvier returneret en int

2022-04-25 18:50 UTC, Determinatoro requested changes
Har sat nogle kommentarer

2022-04-26 07:23 UTC, LivHolm reviewed
Det hele ser ud til at virke.
Overvej at opdater readme med info omkring arguments.
Du for en approve så snart at jakobs forslag er lavet.

2022-04-26 07:25 UTC, JeppeLindberg commented on src/main.py
> +        if len(args) > 2:
Det fungerer som det burdte. Har ændret det lidt så det er lidt mere læsbart.

2022-04-26 07:35 UTC, JeppeLindberg commented
Har rettet disse kommentarer

2022-04-26 07:36 UTC, LivHolm approved these changes

2022-04-26 08:48 UTC, Determinatoro approved these changes

2022-04-26 09:41 UTC, merged