Unit tests
cs-22-sw-8-07/recommender_system pull request #5
Opened 2022-05-02 11:12 UTC by JeppeLindberg

2022-05-02 11:49 UTC, LivHolm approved these changes

2022-05-04 06:54 UTC, Determinatoro requested changes
![udklip](https://user-images.githubusercontent.com/29166051/166634447-62826308-4fa5-4cfd-85c5-49dd381d9750.png)

Der mangler noget code coverage (main.py undtaget samt nogle linjer, som ikke kan blive ramt af test på grund af test_mode flaget)

2022-05-04 10:26 UTC, JeppeLindberg commented
Rettet tests for bedre code coverage

![billede](https://user-images.githubusercontent.com/11889521/166664565-264329c3-e50d-4509-b0bc-dd1e64a833e1.png)

2022-05-04 10:41 UTC, Determinatoro approved these changes

2022-05-04 10:42 UTC, merged